{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.embiodiagnostics.belddemo.beld_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3972346,
          "sha512": "7fdc8b3a633c15a40debfe168c08b937b4da67431e797143df03c43738852a92c4aa1b2aab6e8534a6c84927e3d48866fcfaf1e9ee38d46a26054637a59994c1",
          "sha256": "966c7f0f1eff5e56fdb80c1ec72de00d3f7a6817a701c655b3fd2935b8624098",
          "sha1": "6d0b2df3059a3cb42b5cf6c87fdc68ee2fb0152d",
          "md5": "66d68eac00ac4401ca948197f9debe75"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3972346,
          "sha512": "7fdc8b3a633c15a40debfe168c08b937b4da67431e797143df03c43738852a92c4aa1b2aab6e8534a6c84927e3d48866fcfaf1e9ee38d46a26054637a59994c1",
          "sha256": "966c7f0f1eff5e56fdb80c1ec72de00d3f7a6817a701c655b3fd2935b8624098",
          "sha1": "6d0b2df3059a3cb42b5cf6c87fdc68ee2fb0152d",
          "md5": "66d68eac00ac4401ca948197f9debe75"
        }
      ]
    }
  ]
}
