{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.embiodiagnostics.belddemo.beld_module",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 6300152,
          "sha512": "63afc7f66504d2beb992b046ed0836f1b84473022d474182043f2b95ecf3fb4d7256313d13ad573a5321d739414a1aec354726e69dc8de3498e34bca97cab243",
          "sha256": "a7e44d870d0102f82aa2345ad64a4199b6f84731e16169c1bb8cf82e860678e1",
          "sha1": "c8f741ade3c74828bd1afef2d32fded9c4789858",
          "md5": "1c7fd45e3d97801cdd891eea1de93f46"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-45f6e009110df4f34ec2cf99f63cf73b71b7a420"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 6300152,
          "sha512": "63afc7f66504d2beb992b046ed0836f1b84473022d474182043f2b95ecf3fb4d7256313d13ad573a5321d739414a1aec354726e69dc8de3498e34bca97cab243",
          "sha256": "a7e44d870d0102f82aa2345ad64a4199b6f84731e16169c1bb8cf82e860678e1",
          "sha1": "c8f741ade3c74828bd1afef2d32fded9c4789858",
          "md5": "1c7fd45e3d97801cdd891eea1de93f46"
        }
      ]
    }
  ]
}
